---
- name: Container is running
  docker:
    name: jenkins
    image: "jenkins"
    ports: "49001:8080"
    state: started
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  tags: [jenkins]
