---
- file:
    path: /data/jenkins_home
    state: directory
    owner: vagrant
    mode: 0755

- name: Container is running
  docker_container:
    name: jenkins
    image: "jenkins/jenkins:lts"
    privileged: yes
    user: 1000
    ports: 
    - "49001:8080"
    - "50000:50000"
    state: started
    volumes:
      - /data/jenkins_home:/var/jenkins_home
  tags: [jenkins]
