---
- name: Container is running
  docker:
    name: jenkins
    image: "jenkins:lts-alpine"
    ports: 
    - "49001:8080"
    - "50000:50000"
    state: started
    volumes:
      - jenkins_home:/var/jenkins_home
  tags: [jenkins]
