---
- name: JQ is present
  yum:
    name: jq
    state: present
  tags: [common]
  
- name: Git is present
  yum:
    name: git
    state: present
  tags: [common]	

- name: Pip is present
  yum:
    name: python2-pip
    state: present
  tags: [common]  
  
- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]
