- name: CentOS package is installed
  yum:
    name: docker-engine
    state: present
  tags: [docker]

- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [docker]

- name: CentOS service is running
  service:
    name: docker
    state: running
  tags: [docker]
