---
- name: CentOS package is installed
  yum:
    name: docker
    state: present
  tags: [docker]

- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [docker]

- name: CentOS service is running
  service:
    name: docker
    state: running
  tags: [docker]
  
- name: Install Docker-PY
  pip:
    name: "{{ item }}"
  with_items:
    - six
    - docker-py 

- name: Check for vagrant user
  shell: id vagrant
  register: vagrant_exist	
  
- name: Add vagrant user to docker group
  command: gpasswd -a vagrant dockerroot
  when: vagrant_exist  
  
- name: Set owner for docker.sock
  command: chown root:dockerroot /var/run/docker.sock
  when: vagrant_exist  
